; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps = 
	M5Cardputer=https://github.com/m5stack/M5Cardputer
	fastled/FastLED@^3.3.3
build_flags =
    -DCARDPUTER

[env:m5stick]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
board_build.flash_size = 8MB
lib_deps =
    m5stack/M5Unified@^0.2.7
    fastled/FastLED@^3.3.3

[env:m5stack-sticks3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
lib_deps =
    M5Unified=https://github.com/m5stack/M5Unified.git#develop
    fastled/FastLED@^3.3.3